# Generated by Django 3.2.5 on 2022-06-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='desc',
            field=models.CharField(default='no desc', max_length=255),
        ),
        migrations.AddField(
            model_name='table',
            name='title',
            field=models.CharField(default='no title', max_length=100),
        ),
    ]
