# Generated by Django 3.2.5 on 2022-06-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_auto_20220613_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='desc',
            field=models.CharField(blank=None, default='no desc', max_length=255),
        ),
        migrations.AlterField(
            model_name='table',
            name='title',
            field=models.CharField(blank=None, default='no title', max_length=100),
        ),
    ]
