# Generated by Django 3.2.5 on 2022-06-27 15:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_auto_20220627_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='Datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 27, 15, 25, 38, 263637, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='table',
            name='desc',
            field=models.CharField(default='no desc', max_length=255),
        ),
        migrations.AlterField(
            model_name='table',
            name='title',
            field=models.CharField(default='no title', max_length=100),
        ),
    ]
